name: tf1
channels:
  - defaults
dependencies:
  - matplotlib
  - numpy
  - pandas
  - python=3.6.10
  - scikit-learn
  - scikit-learn-intelex
  - scipy
  - pip
  - black
  - pylint
  - pip:
      - jupyter
      - tensorflow==1.15.0
      - tensorboard==1.15.0
