name: m1
dependencies:
  - apple::tensorflow-deps
  - bleach
  - certifi
  - colorama
  - cycler
  - decorator
  - entrypoints
  - html5lib
  - ipykernel
  - ipython
  - ipython_genutils
  - ipywidgets
  - jedi
  - jinja2
  - jsonschema
  - jupyter
  - jupyter_client
  - jupyter_console
  - jupyter_core
  - markupsafe
  - matplotlib
  - mistune
  - nbconvert
  - nbformat
  - notebook
  - numpy
  - pandas
  - pandocfilters
  - path.py
  - pickleshare
  - pip
  - prompt_toolkit
  - pygments
  - pyparsing
  - python
  - python-dateutil
  - pytz
  - pyzmq
  - qtconsole
  - requests
  - scikit-learn
  - scipy
  - setuptools
  - simplegeneric
  - sip
  - six
  - testpath
  - tornado
  - traitlets
  - wcwidth
  - wheel
  - widgetsnbextension
  - pip:
      - ipython-genutils
      - jupyter-client
      - jupyter-console
      - jupyter-core
      - markdown
      - prompt-toolkit
      - protobuf
      - tensorflow
      - tensorflow-macos
      - tensorflow-metal
      - tensorflow-tensorboard
      - werkzeug
